#spring:
#  datasource:
#    url: jdbc:mySql://localhost:3306/jwt_security
#    username: root
#    password: root
#    driver-class-name: org.mysql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.mySQLDialect